### ISSUE TITLE
Tree-Based CAM toolpath preview bad DPI

### ISSUE THREAD

**Issue by emteeoh** [openhardwarecoza/LaserWeb3#93] opened 2016-08-15 16:21 UTC
Steps to reproduce:
load a 90dpi image
go to TBC
create a toolpath
configure toolpath
select preview toolpath
==> the toolpath is at 25.4DPI, but the SVG is at 90.

**Comment by ghost** [comment] 2016-08-15 16:32
https://plus.google.com/+S%C3%A9bastienMischler-Skarab/posts/WcbDEKyS6gW related.   Sort of duplicate of #94

**Comment by emteeoh** [comment] 2016-08-15 16:39
I don't think its a duplicate of 94. In 94, the image is loaded correctly, but the DPI is incorrectly displayed but only initially. Here in 93, everywhere I look, the DPI says 90, but the preview toolpath seems to be ignoring the 90 using 25.4 instead. Even if I edit the DPI of an image and explicitly set it to 90, the toolpath still incorrectly renders.

**Comment by ghost** [comment] 2016-08-15 16:43
Not the same but steadily related.

**Comment by ghost** [comment] 2016-10-06 17:46
Is this issue still an issue?

**Closed as completed** 2016-10-23 07:42 UTC
Labels: bug
