### ISSUE TITLE
Error when opening gcode file in Laserweb

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#109] opened 2016-09-05 17:29 UTC
If I open an existing gcode file in LaserWeb, the following error is displayed in the terminal:

ReferenceError: boundingBox is not defined (http://192.168.0.101:8000/js/tabs.js on line 97)

The file seems to load ok however, it shows up in the all layers tab, but it does not display anything in ther Gcode view tab.

**Comment by ghost** [comment] 2016-09-05 17:31
Since a gcode file is but a layer.  Click generate gcode on cam tab to
populate the 'gcode tab'  and prep job for sending.

**Comment by funinthefalls** [comment] 2016-09-06 01:34
Still does not populate the "gcode view" tab (tab on the top) after clicking "generate gcode" on the cam tab. And in the Gcode tab on the left (not to confuse it with the gcode view tab at the top) It has a "Start Gcode" box, a "Gcode opened from file" box, and a "gcode end" box.

**Comment by ghost** [comment] 2016-10-23 07:44
Duplicate of https://github.com/openhardwarecoza/LaserWeb3/issues/163

**Closed as completed by ghost** 2016-10-23 07:44 UTC
Labels: enhancement
