### ISSUE TITLE
laserweb3 no port

### ISSUE THREAD

**Issue by gbrinki** [openhardwarecoza/LaserWeb3#231] opened 2017-02-15 16:53 UTC
after installation and settings i have no possibility to choose a serial port.
second probllem
![problem](https://cloud.githubusercontent.com/assets/25793420/22985020/7df0ed20-f3a7-11e6-85d0-7e586fd760b8.JPG)
wich pin is asked to get the mashine started?

**Comment by tbfleming** [comment] 2017-02-15 17:19
@openhardwarecoza This is a recurring user error. Maybe the PIN should default to disabled. I doubt the PIN is good for safety since machines tend to have a physical test laser button.

**Comment by ghost** [comment] 2017-02-15 17:31
This particular instance is an JS error somewhere in the stack (if pin is a text field instead of how it looks if the jquery plugin ran)

When theres JS errors in the stack, things stop working (ie hiding pin, threejs, jquery for the port selection, etc) 

So @gbrinki , read the syslog near the top and tell us what it says

**Comment by ghost** [comment] 2017-02-15 17:32
If there were no errors (webgl started, etc) the Pin field renders like this when the JQuery plugin takes it over... 

![if plugin ran](https://cloud.githubusercontent.com/assets/7695323/22986839/759cdfcc-f3b5-11e6-98cf-207271604c68.PNG)

**Comment by ghost** [comment] 2017-02-15 17:34
Ctrl+shift+i console during a refresh may tell you more too
![healthy start](https://cloud.githubusercontent.com/assets/7695323/22986914/b9930d64-f3b5-11e6-909f-4d0b226fc9f9.PNG)


If your log has errors, it will do what i see above

**Comment by ghost** [comment] 2017-02-15 17:36
Now, closing this as its not a bug, just a plain support question, and the README does tell you where to go for that

![wrong place](https://cloud.githubusercontent.com/assets/7695323/22986978/f74d5cb8-f3b5-11e6-86ce-a0a55593730b.PNG)



(If you didnt read the readme, what else didnt you read (;   - maybe thats why its not working.  Ie must be Chrome, must be on a machine with good webgl support, etc)

**Closed as completed by ghost** 2017-02-15 17:36 UTC

**Comment by gbrinki** [comment] 2017-02-17 16:05
thank you for your mail. Now I have made 3 screenshots of my Laserweb3
console. I do not know exactely but i think there have been found two
mistakes but i do not know how to handle them and would be glad if you can
help me, Thanks!

2017-02-15 18:36 GMT+01:00 Peter van der Walt <notifications@github.com>:

**Comment by gbrinki** [comment] 2017-02-17 16:11
![laserwebconsole1](https://cloud.githubusercontent.com/assets/25793420/23072983/1d5dc88c-f534-11e6-995c-4ecf46f3302a.JPG)
![laserwebconsole2](https://cloud.githubusercontent.com/assets/25793420/23072982/1d560c50-f534-11e6-98e8-cdb57f6c28ad.JPG)
![laserwebconsole3](https://cloud.githubusercontent.com/assets/25793420/23072981/1d55aab2-f534-11e6-9b2e-b7371d945def.JPG)

**Comment by tbfleming** [comment] 2017-02-17 16:12
@gbrinki Please reread the text @openhardwarecoza highlighted in yellow before he bans you.

**Comment by ghost** [comment] 2017-02-17 16:33
(; yeah I am getting close... 
Itching on the ban button

Anyway, thats a browser plugin preventing websocket access... Use a clean install of chrome without shit installed

Or server.js is not running
