### ISSUE TITLE
object to default parameters when importing new object

### ISSUE THREAD

**Issue by fumblz-n-action** [openhardwarecoza/LaserWeb3#114] opened 2016-09-07 05:51 UTC
I imported an image and sized it accordingly and gave it an off set. next i imported another object (dxf file) then image file reverted back to its defaulted original imported size and placement,

**Comment by krolco** [comment] 2016-09-07 06:01
I am able to reproduce this. Someone (maybe me?) will have a look.

**Comment by krolco** [comment] 2016-09-07 16:14
OK, I've been looking at the code, and I think is a side-effect of an earlier feature that I did ( #104).
I have to think about how to fix this a bit more. I'll try to look at it again tonight.

**Comment by krolco** [comment] 2016-09-08 06:05
Ok, I just merged #120 that should finally fix this -- I didn't quite get it right the first time, but I spent more time grokking the code, and it should work now. I was accidentally resetting the raster's position anytime another object was added to the scene (because I didn't understand that I added the code in a spot that made a pass over all objects every time something was added to the scene, instead of once at first add). @fumblz-n-action, please test this now if you can.

**Comment by cojarbi** [comment] 2016-09-08 12:36
I can confirm

**Comment by krolco** [comment] 2016-09-09 18:21
Does this seem OK now? I'd like to close it if possible. @cojarbi @fumblz-n-action Thank you!

**Comment by cojarbi** [comment] 2016-09-09 18:38
I did check it and passed fine

AY

**Comment by krolco** [comment] 2016-09-09 20:18
Thank you. I'm going to close this one then.

**Closed as completed** 2016-09-09 20:18 UTC
Labels: PLEASE TEST
